[package]
name = "timeseries-lsm"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.5"
crc32fast = "1.3"
crossbeam = "0.8"
parking_lot = "0.12"
snap = "1.1"
thiserror = "2.0.17"
probabilistic-collections = "0.7" 

[dev-dependencies]
tempfile = "3.23.0"
